-- EduVia application schema. Apply to the Supabase project's Postgres database.
-- Kept intentionally additive so it can be applied to an existing project.

create table if not exists public.users (
  id integer generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  name text not null,
  role text not null check (role in ('student','tutor')),
  headline text not null default '',
  bio text not null default '',
  hue integer not null default 348,
  created_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  is_admin integer not null default 0,
  email_verified_at text
);

create table if not exists public.tutor_profiles (
  user_id integer primary key references public.users(id) on delete cascade,
  expertise text not null default '',
  credentials text not null default ''
);

create table if not exists public.subscriptions (
  id integer generated by default as identity primary key,
  user_id integer not null unique references public.users(id) on delete cascade,
  plan text not null check (plan in ('monthly','annual','family')),
  status text not null check (status in ('active','canceled','past_due')),
  payment_reference text not null default '',
  current_period_end text,
  created_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);

create table if not exists public.classes (
  id integer generated by default as identity primary key,
  tutor_id integer not null references public.users(id) on delete cascade,
  slug text not null unique,
  title text not null,
  subtitle text not null default '',
  description text not null default '',
  category text not null default 'other',
  level text not null default 'beginner',
  hue integer not null default 348,
  status text not null default 'draft' check (status in ('draft','published')),
  created_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  cover_hue integer not null default 348
);

alter table public.users add column if not exists is_admin integer not null default 0;
alter table public.users add column if not exists email_verified_at text;
alter table public.classes add column if not exists cover_hue integer not null default 348;

create table if not exists public.lessons (
  id integer generated by default as identity primary key,
  class_id integer not null references public.classes(id) on delete cascade,
  position integer not null,
  title text not null,
  duration_seconds integer not null default 600,
  video_url text not null default '',
  is_preview integer not null default 0,
  unique (class_id, position)
);

create table if not exists public.enrollments (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  class_id integer not null references public.classes(id) on delete cascade,
  created_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  unique (user_id, class_id)
);

create table if not exists public.lesson_progress (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  lesson_id integer not null references public.lessons(id) on delete cascade,
  completed integer not null default 0,
  position_seconds integer not null default 0,
  updated_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  unique (user_id, lesson_id)
);

create table if not exists public.settings (
  user_id integer primary key references public.users(id) on delete cascade,
  autoplay integer not null default 1,
  playback_speed double precision not null default 1,
  captions integer not null default 0,
  email_classes integer not null default 1,
  email_essays integer not null default 0,
  marketing integer not null default 0,
  theme text not null default 'dark',
  updated_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);

create table if not exists public.reviews (
  id integer generated by default as identity primary key,
  class_id integer not null references public.classes(id) on delete cascade,
  user_id integer not null references public.users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  body text not null default '',
  status text not null default 'published' check (status in ('published','hidden')),
  created_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  unique (class_id, user_id)
);

create table if not exists public.wishlist (
  user_id integer not null references public.users(id) on delete cascade,
  class_id integer not null references public.classes(id) on delete cascade,
  created_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  primary key (user_id, class_id)
);

create table if not exists public.notifications (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  kind text not null,
  title text not null,
  body text not null default '',
  link text not null default '',
  read_at text,
  created_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);

create table if not exists public.certificates (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  class_id integer not null references public.classes(id) on delete cascade,
  code text not null unique,
  recipient text not null,
  issued_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  unique (user_id, class_id)
);

create table if not exists public.questions (
  id integer generated by default as identity primary key,
  class_id integer not null references public.classes(id) on delete cascade,
  user_id integer not null references public.users(id) on delete cascade,
  parent_id integer references public.questions(id) on delete cascade,
  body text not null,
  answer text,
  answered_at text,
  created_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);

create table if not exists public.auth_tokens (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  purpose text not null check (purpose in ('reset','verify')),
  token_hash text not null unique,
  expires_at text not null,
  used_at text,
  created_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);

create table if not exists public.earnings (
  id integer generated by default as identity primary key,
  tutor_id integer not null references public.users(id) on delete cascade,
  class_id integer references public.classes(id) on delete set null,
  student_id integer references public.users(id) on delete set null,
  amount_cents integer not null,
  reason text not null,
  created_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);

create table if not exists public.promo_codes (
  id integer generated by default as identity primary key,
  tutor_id integer not null references public.users(id) on delete cascade,
  code text not null unique,
  percent_off integer not null check (percent_off between 1 and 100),
  max_uses integer not null default 0,
  used_count integer not null default 0,
  expires_at text,
  created_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);

alter table public.classes
  add column if not exists promo_code_id integer references public.promo_codes(id) on delete set null;

create table if not exists public.transcripts (
  lesson_id integer primary key references public.lessons(id) on delete cascade,
  body text not null default '',
  updated_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);

create table if not exists public.lesson_notes (
  user_id integer not null references public.users(id) on delete cascade,
  lesson_id integer not null references public.lessons(id) on delete cascade,
  body text not null default '',
  seconds integer not null default 0,
  updated_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  primary key (user_id, lesson_id)
);

create table if not exists public.moderation_log (
  id integer generated by default as identity primary key,
  admin_id integer not null references public.users(id) on delete cascade,
  action text not null,
  entity_type text not null,
  entity_id integer not null,
  note text not null default '',
  created_at text not null default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);

create index if not exists idx_classes_tutor on public.classes(tutor_id);
create index if not exists idx_lessons_class on public.lessons(class_id);
create index if not exists idx_enroll_user on public.enrollments(user_id);
create index if not exists idx_progress_user on public.lesson_progress(user_id);
create index if not exists idx_reviews_class on public.reviews(class_id, status);
create index if not exists idx_notifications_user on public.notifications(user_id, read_at);
create index if not exists idx_questions_class on public.questions(class_id, parent_id);
create index if not exists idx_auth_tokens_user on public.auth_tokens(user_id, purpose);
create index if not exists idx_earnings_tutor on public.earnings(tutor_id, created_at);
create index if not exists idx_modlog on public.moderation_log(created_at);

-- The app accesses Postgres through its private server connection. Block direct
-- access through Supabase's public Data API until explicit policies are added.
alter table public.users enable row level security;
alter table public.tutor_profiles enable row level security;
alter table public.subscriptions enable row level security;
alter table public.classes enable row level security;
alter table public.lessons enable row level security;
alter table public.enrollments enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.settings enable row level security;
alter table public.reviews enable row level security;
alter table public.wishlist enable row level security;
alter table public.notifications enable row level security;
alter table public.certificates enable row level security;
alter table public.questions enable row level security;
alter table public.auth_tokens enable row level security;
alter table public.earnings enable row level security;
alter table public.promo_codes enable row level security;
alter table public.transcripts enable row level security;
alter table public.lesson_notes enable row level security;
alter table public.moderation_log enable row level security;
